version: "3"

services:
  backend:
    build: backend/
    ports:
      - 8080:8080
    networks:
      - local-thor

  node:
    image: vechain/thor
    entrypoint: ["thor", "--network", "test", "--api-addr", "0.0.0.0:8669"]
    volumes:
      - data/.org.vechain.thor:/root/.org.vechain.thor
    networks:
      - local-thor
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.25"
          memory: 3gb

networks:
  local-thor:
    driver: bridge

volumes:
  data: