version: "3"

services:
  backend:
    build: backend/
    ports:
      - 8080:8080
    networks:
      - local-thor

  node:
    image: vechain/thor
    entrypoint: ["thor", "--network", "test", "--api-addr", "0.0.0.0:8669"]
    volumes:
      - data/.org.vechain.thor:/root/.org.vechain.thor

volumes:
  data: