version: "3"

services:
  backend:
    build: backend/
    ports:
      - 8080:8080
    networks:
      - local-thor
    environment:
      - THOR_ENDPOINT=node
      - THOR_PORT=8669

  frontend:
    build: frontend/
    ports:
      - 3000:3000

  node:
    image: vechain/thor
    entrypoint: ["thor", "--network", "test", "--api-addr", "0.0.0.0:8669"]
    volumes:
      - ./data:/root/.org.vechain.thor
    networks:
      - local-thor
    # ports:
    #   - 8669:8669
    #   - 11235:11235
    #   - 11235:11235/udp
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.25"
          memory: 3gb

networks:
  local-thor:
    driver: bridge
