name: abc

on:
  push:
    branches: [main]

jobs:
  build-frontend:
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    name: Build with ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build

  build-backend:
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    name: Build with ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build